### ISSUE TITLE
Use 2 dimensional lists

### ISSUE THREAD

**Issue by ElVit** [home-assistant/tempio#18]
Hi is it possible to use 2 dimensional lists with tempio?

For example:
```
"logins": 
    [
      { "username": "user1", "password": "1234" },
      { "username": "user2", "password": "5678" }
    ]
```

And then insert all usernames to a template:
`valid users = /{{ .logins.username | join "," }}/`

**Comment by ludeeus** [comment]
`valid_users = {{$equipment := .logins}}{{ range $index, $element := .logins}}{{if $index}},{{end}}{{$element.username}}{{end}}`
