### ISSUE TITLE
non-file output

### ISSUE THREAD

**Issue by frenck** [home-assistant/tempio#5]
I think it would be a nice addition, if tempio could output the resulting template (instead of writing to a file), in case no `-output` flag was specified.

This could be helpful in cases to render content that is not stored on disk (but, for example, send to a webservice of some kind).

It is more of an suggestion, not a real issue. Maybe I get to it myself one day. No rush at all.

**Comment by pvizeli** [comment]
I don't see a reason why not. I think it makes sense to write into stout if there is no `-output` like we do with stdin and `-input`

**Comment by frenck** [comment]
Not stale

**Comment by frenck** [comment]
Thanks, @ludeeus ❤️
